using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdventOfCode
{
    public class Day12
    {
        public static int Main12(string[] args)
        {
            string input = Day12.Input;
            char[][] field;
            string errorMessage;

            if (!Day12.TryParse(input, out field, out errorMessage))
            {
                Console.WriteLine(errorMessage);
                Console.ReadKey();
                return 1;
            }

            bool[][] visited = new bool[field.Length][];
            for (int row = 0; row < field.Length; ++row)
            {
                visited[row] = new bool[field[row].Length];
            }

            int costPerim = 0;
            int costSides = 0;
            for (int row = 0; row < field.Length; ++row)
            {
                for (int col = 0; col < field[row].Length; ++col)
                {
                    if (!visited[row][col])
                    {
                        var areaPerimSides = FenceParemeters(ref field, ref visited, row, col);
                        costPerim += areaPerimSides.Item1 * areaPerimSides.Item2;
                        costSides += areaPerimSides.Item1 * areaPerimSides.Item3;
                    }
                }
            }

            Console.WriteLine($"costPerim: {costPerim}, costSides: {costSides}");
            return 0;
        }

        // returns [area, perimeter, sides]
        private static Tuple<int, int, int> FenceParemeters(ref char[][] field, ref bool[][] visited, int row, int col)
        {
            if (visited[row][col])
            {
                return new Tuple<int, int, int>(0, 0, 0);
            }

            visited[row][col] = true;
            int area = 1; // this cell
            int perim = 0; // no intrinsic border
            int corners = 0; // equal to number of sides

            bool borderRight = false;
            bool borderTop = false;
            bool borderLeft = false;
            bool borderBottom = false;

            if (row > 0 && field[row - 1][col] == field[row][col])
            {
                var paramsAdj = FenceParemeters(ref field, ref visited, row - 1, col);
                area += paramsAdj.Item1;
                perim += paramsAdj.Item2;
                corners += paramsAdj.Item3;
            }
            else
            {
                perim += 1;
                borderTop = true;
            }

            if (row < field.Length-1 && field[row + 1][col] == field[row][col])
            {
                var paramsAdj = FenceParemeters(ref field, ref visited, row + 1, col);
                area += paramsAdj.Item1;
                perim += paramsAdj.Item2;
                corners += paramsAdj.Item3;
            }
            else
            {
                perim += 1;
                borderBottom = true;
            }

            if (col > 0 && field[row][col - 1] == field[row][col])
            {
                var paramsAdj = FenceParemeters(ref field, ref visited, row, col - 1);
                area += paramsAdj.Item1;
                perim += paramsAdj.Item2;
                corners += paramsAdj.Item3;
            }
            else
            {
                perim += 1;
                borderLeft = true;
            }

            if (col < field[row].Length - 1 && field[row][col + 1] == field[row][col])
            {
                var paramsAdj = FenceParemeters(ref field, ref visited, row, col + 1);
                area += paramsAdj.Item1;
                perim += paramsAdj.Item2;
                corners += paramsAdj.Item3;
            }
            else
            {
                perim += 1;
                borderRight = true;
            }

            // inward corners
            if (borderRight && borderTop) ++corners;
            if (borderTop && borderLeft) ++corners;
            if (borderLeft && borderBottom) ++corners;
            if (borderBottom && borderRight) ++corners;

            // outward corners
            if (!borderRight && !borderTop && row > 0 && col < field[row].Length - 1 && field[row - 1][col+1] != field[row][col]) ++corners;
            if (!borderTop && !borderLeft && row > 0 && col > 0 && field[row - 1][col - 1] != field[row][col]) ++corners;
            if (!borderLeft && !borderBottom && row < field.Length && col > 0 && field[row + 1][col - 1] != field[row][col]) ++corners;
            if (!borderBottom && !borderRight && row < field.Length && col < field[row].Length - 1 && field[row + 1][col + 1] != field[row][col]) ++corners;

            return new Tuple<int, int, int>(area, perim, corners);
        }

        private static bool TryParse(string input, out char[][] field, out string errorMessage)
        {
            errorMessage = null;
            field = null;

            if (input.Length == 0)
            {
                errorMessage = "Input cannot be empty";
                return false;
            }

            var lines = input.Split("\r\n");
            var fieldTemp = new char[lines.Length][];
            for (int i = 0; i < lines.Length; ++i)
            {
                fieldTemp[i] = new char[lines[i].Length];
                for (int j = 0; j < lines[i].Length; ++j)
                {
                    if (!char.IsLetter(lines[i][j]))
                    {
                        errorMessage = $"Crop type not supported: '{lines[i][j]}'.";
                        return false;
                    }
                    fieldTemp[i][j] = lines[i][j];
                }
            }

            field = fieldTemp;
            return true;
        }

        private const string Example = "RRRRIICCFF\r\nRRRRIICCCF\r\nVVRRRCCFFF\r\nVVRCCCJFFF\r\nVVVVCJJCFE\r\nVVIVCCJJEE\r\nVVIIICJJEE\r\nMIIIIIJJEE\r\nMIIISIJEEE\r\nMMMISSJEEE";
        private const string Input = "WWWWWWWWWWWWWWWWWWHHHHHHHHHHHBYYYYYYYYYYYJJJJJJJJJJJJJJZLLLLLLLLLLLLLLLLLLLLLLBBYBBBBBBBBTTTTKKKKKKKKKKKKKOOOUUUUUUUUUUUSSSSSSSSSSSSSSSSSSSO\r\nWWWWWWWWWWWWWWWWWWHEHEHHHHHHBBBYYYYYYYYYYJJJJJJJWJJZJZZZZLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBTTTKKKKKKKKKKKKKOOOUUUUUUUUUUUUSSSSSSSSSSSSSSSSSHH\r\nWWWWWWWWWWWWWWWWWWWEEEHHHHHBBBBBYYYYYYYYYJYJJJJWWJJZZZZZZLLLFFFLLLFLLLHHHHHHHLBBBBBBBBBBBBTTTKKKKKKKKKKKKKOOOOUUUUUUUUUSSSSSSSSSSSSSSSSSSSHH\r\nWWWWWWWWWWWWWWWWWEEEEEEEEHHBBBSSYYYYYYYYYYYWWWWWWJJZZZZZZLFLFFFFFLFFFLHHHNHHHHABBBBBBBBBBBTTKKKKKKKKKKKKKKOOOUUUUUUUUUUSSSSSSSSSSSSSSSSSHHHH\r\nWWWWWWWWWWWWWWGEEEEEEEEHEHHHHHHSYYYYYYYYYYYYWWWWWWZZZZZZFFFFFFFFFFFFLLLHHNHHHHABBBBBBBBBBBTTKKKKKKKKKKKKKKKOOUUUUUUUSSSSSSSSSSSSSSSSSSSSHHHH\r\nWWWWWWWWWWWWWWWEEEEEEEEHHHHHHHHSSSYYYYYYYYYWAWWWWWWZZZZFFFFFFFFFFFFHHHLHHHHHHAABBBBBBBBBBBBTKKKKKKKKKKKKKKKOOFUUUUUUUUUSUUSSSSSSSSSHHHHHHHHH\r\nWWWWUWWWWWWWWWWWEEEEEEEHHHHHHHHSSSSSYYYWWYYWAWWWWWWZZZZFFFFFFFFFFFFFHHHHHHHHHBABBBBBBBBBBBBBBKKKKKKKKKKKKKKFFFFUUUUUUUUUUSSSSSSSSSSHHHHHHHYY\r\nWWWWWWWWWWWWWWWWEEEEEEEEHHHHSSSSSSSSYYYWWWWWWWWWWDWWWZZFFFFFFFFFFFFFHHHHHHHHHBABBBBBBBBBBBBBBPPPKKKKKKKKKKKKFFAFUUUUUUUUSSSSSSSSSSSHHHHHHHHY\r\nWEEEWWWWWWWWWWWEEEEEEEEHHHHHHSSSSSSSYSSWWWWWWWWWWDDDZZZFFFFFFFFFFFFHHHHHHHHHHBBBBBBBBBBBBBBBPPPPKKKKKKKKKKKKFFFFVUUUHHHSSSSSSSSSSSHHHHHHHHHH\r\nEEEEWWWWWWWWEEEEEEEEEREEHHHHHSSSSSSSSSMWWWWWWWWWWWDDDDFFFFFFFFFFFFFHHHHHHHHHHHBBBBBBBBBBBBBBPPPPPPKKKKKKKKKOFFFFUUUUHHHSSSSOSSDSSSHHHHHHHHHH\r\nEEEEEWWWWWXWEEEEEEERRRRHHHHSSSSSSSSSSSWWWWWWWWWWWWCCCDDFFFFFFFFFFFFFHHHHHHHHHHBHHBBBBBBBBBBBPPPPPPPKKKFFFKFFFFVFUUUHHHHSSHHOODDSSSHRHHHHHHHH\r\nEEEEEWWWWWWJJEJEEEERRRHHHHHRRSSSSSSSSSMMWWWWWWWWWCCCCCCFFFFFFFFFFFFFFHHHHHHHHHHHHBBBBBBBNNBGPPPPPPPPPKFFFFFFFFVVVUHHHHHHHHHOODDSRRRRHHHHHHHH\r\nEEEEEWEWZZJJJJJJEEERRRRRRRHRHSSSSSSSSSSWWWWWWWWCCCCCCCXXFFFFFFFFFFFFFHHHHHHHHHHHHHNNNBBNNNNPPPPPPPPPPPFFFFFFFFFVVHHHHHHHHHOHOOORRRRRHHHHHHHH\r\nEEEEEEEIIIJJJJOOJJRRRRRRRRRRRRRSSSSSSSSWSWWWWCWCCCCCCCXXXFFFMYMMMFFFFHHHHHHHHHHHHHHLNNNNNNPPPPPPPPPPPPPFFFFFFFFVHHHMHHHHHHOOOOORORHHHHHHHHWW\r\nQEEEEIIIIIIJJJJJJJVRRRRRRRRRRRRSSSSSSSSSSWWWCCCCCCCCCCXXXFFFMMMMMMFFHHHHHHHHHHHHHHLLNNNNNNNPQPPPPPPPPPPFFFFFFFFHHHMMMMMMHHOOOOOOORRHHHHHHWWW\r\nQQQEEIIIIIIJJJJJJJRRRRRRRRRRRRRSSSSSSSSSSWWWCCCCCCCCCCXXXFSFFMMMMMUUTHHTTHHHHHHHHLLLLLNDDNNNPPPPPPPPPPPPPFFFFFFFFMMMMMMMHOOOOOOOOHHHHHHHHHWW\r\nQQQEEIIIIJJJJJJJJBRRRRRRRRRRRRRRSSSSSSSSWWCCCCCCCCCCXXXXXSFFFMMMMMMUTTTTTHHTHHHHLLLLKNNDDNNNNPPPPPPPPPPPPFFFFFFFFMMMMMMWOOOOOOOOOHDDDHHHHWWW\r\nQQQQEJJJIJJJJJJJJRRRRRRRRRRRWRTSSSSSSSSSSCCCCCCCCCCCCXXXXSSFFMMMMMMMMTTTTTTTLDLLLLLLKKDDNNNNNNPPPPPPPPPPFFFFZFMMMMMMMMMOOOOOOOOOOZODDHHHHWWW\r\nQQQQJJJJJJJJJJJJJJJRRRRRRRURRRTSSSSSSSSSSSSCCCCCCCCCCCCXXSSSMMMMMMMMMMTTTTTLLLLLLLLLLDDDDDDNNNPPPPPPPPPPFFFFFMMMMMMMMMMTOOOOOOOOOOODDDDHHDDW\r\nQQQQJJJJJJJJJJJJJJRRRRRRRRURMRSSSSSSSSSSSSSCCCCCCCCCCCCXXSSSMMMMMMMMMMQTTTTTLLLLLLLLLDDDDDDNNNPPPKPPPPPTFFFFFMMMMMMMMMMTTOOOOOOOOODDDDHHHDDW\r\nQQQJJJJJJJJJJJJJJJJBBBRRRRRRRSSSSSSSSSSSSSCCCCCCCCCCHSSSSSSSMMMMMMMMMQQQTTLTLLLLLLLLLDDBDDDNNPPPPPPPPPPTFFFFMVMMMMMMMMEOOOOOOOOOOOOOODDHHDDW\r\nQQQQQQQJJJJJJJJJJJJBBBJRRRRRRSSSSSSSSSSSSSSCCCCCYYCCHHYSSSSSSMMMMMMMMQQQLLLLLLLLLLLLDDDBBWDNHHPPPPIHPPPTTTFFMMMMMMMMMEEOOOOOOOOOOOOODDDDDDDD\r\nQQQQQJJJJJJJJJJJJJJBBBJRRRRYSSYSSSSSSSSHHHYYCCCCYYYHHYYSSSSSSSMMMMMMQQQQQQLLLLIILLLLDDDBBBBNHHPPPPPHHHPHTTMMMMMFMMMMMTTOOOOOOOOOOOODDDDDDDDZ\r\nQQQQQQQJJJJJJJJJJJJBBBJKKKRYYYYYSSSSHHHHHHYYCCCYYYYYYYYYSSSSSSSMSSSQQQQQQQQQLLLLLDDDDDBBBBBBHHHPPPHHHHHHTLLLTTMMMMMMMMTOOOOOOOOOOOOODGDDDDDZ\r\nQQQQQQQJJJJJJJJJJJJBBBJJKJYYYYYYYSSSSHHHHHHYYYYYYYYYYYYYZSSSSSSMSQQQQQQQQQQQJLLDDDDBBBBBBBBBBHHHHHHHHHHHHLLLTTMMMMMMMTTOTTWOOLOHGGGGGGGGDDSZ\r\nQQQQQQQQQJVVAAJJJJJBBBJJJJYYYYYYYYSSHHHHHHHYYWWWWWWWWWKYSSSSSSSSSSSSQQQQQQQQQQLLDDDBBBBBBBPBBHHHHHHHHHHHHLLLTTTTTMTTMMTTTWWWOGGGGGGGGGGGDDSS\r\nQQQQQQQQQQVVQAAAJJJBBBJJJJJYYYYYYYHHHHHHHHHYYWWWWWWWWWYSSSSSSSSSSSSSQQQQQRQDDDDDDDDBBBBBPBPBHHHHHHHHHLLLHLLLTTTTTMTTTTTTTWWWWWWGGGGGAAGGDSSS\r\nQQQQQQQQQQQQQAAAYJJBBBJJJPJYYYYYYYYHHHHHHVYYWWWWWWWWWWYSSSSSSSSSSSSSQQQQRRDRRRDDDDDBBPBPPBPPHHHHHHHHHHLLLLLLZTTTTTTTTTTTTTWWWWWWWGGGAAAGGSSS\r\nAQQQQQQQQQQQAAAYYJJJJJJJJJYYYYYYYYYHHHHHHHYYWWWWWWWWWWYSSSSSSSSSSSSSQQQQQRRRRDDDDDDBDPPPPPPHHHHHHHHHHHLLLLZZZTTTTTTTTTTTTTWWWWWWWGGGAAASSSSS\r\nAAAQQQQQQQQQYYYYYJJJJJJUJJYYYYYYYYYLHHHHHHHYWWWWWWWWWWYYSSSSSSSSSSSSQQQQQRRRRDDDDDDDDPPPPPPZHHHHHHLLLHLLLLZZZTTTTTTTTTTTTTWWWPWWWWGGGAAASSSS\r\nAAAQQQQYOYYBYYYYYYYJJJUUJJYYYYYYYYLLLLLWWWWWWWWWWWWWWWYYSSSSSSSSSQQQQQQQQRRRRRDDDDDDQQPPPZPZHHHHHHLLLLLLLZZZZZZZTTTTTTTTTWWWWPPPPPPPPPPASSAA\r\nAAAAAQJYYYYYYYYYUKUJJUUNJJJYYYYYYYLLLLLWWWWWWWWWWWWWWWRSSSSSSSPPSSXXQQQQQRRRRDDDDDDDQPPZZZZZZHHHHHHLLLLLLZZZZZZZZTTTBBBBWWWWWPPPPPPPPAAASSSA\r\nAQAAAAYOYYYYYYIUUUUUJUUUYYYYYYYWLLLLLLLWWWWWWWWWWWWWWWRSSSSSSSAPPXXXPQQYYYRADDDDDDDDQQZZZZZZZHHZLLLLLLLLZZZZZZZZZTTTBBBWWWWWWWPPPPPPPAAAAASA\r\nAQAQQAYYYYYYYYIYYUUUUUOUUYYYYYWWLLLLLLLWWWWWWWWWWWWWWWRSSSSSSSPPPPPPPQYYYYRDDDDDDQQQQCQQZZZZZZZZLLLLLLLZZZZZZZZZZBBBBBBBBBBWWWPPPPPPPAAAAAAA\r\nAQQQQQYYYYYYYYYYYUUUUUUUUUUUYYWWVLLLLLLWWWWWWWWWWWWWWWRSSSSSSSPPPPPPPPPPYYYDDDDDDQQQQQQQQZZZZZSSSLLLSLLLLZZZZZZZUZZBBBBBBBBBWZPPPPPPPPAAAAAA\r\nQQQQQYYYYYYYYYYYYUUUUUUUPUUUUWWWWWDLLLLWWWWWWWWWWWWZZZTTPSTTTTTTTTTPPPOOOOOOODODDQQQQQQQQZZZZSSSSLSSSSLLLZZZZZZZZZBBBBBBBBBBZZZZPPPPPAAAAAAA\r\nQQQQQRYYYYYYYYYYYYUUUUUUUUUUUWWWWWWLLLLLWWWWWWWWWWWSSSTTTTTTTPTTTTTPPPOOOOOOOOODDQQQQQQQQQZZZSSSSSSSSSLLZZZZZZZZZJBBBBBBBBBBZZZZZPPPPAAAAAAA\r\nQQQQYYYYYYYYYYYYYYUUUUUUUUUUUWWWWWWLLLLLLLLLWWWSSSSSSTTTTTTTTTTTTTTPPPOOOOOOVOOODQQQQQQQQZZZZSSSSSSSSSLZZZZZZZZZZBBBBBBBBBBBZZZZZZZZZZZAAAAA\r\nQQQQYMMYYYYYYYYYYYUUUUUUUUUUUUWWWWWWLLLLPPPLWWWSSSSSSFTFTTTTTTTTTTTPPPOOOOOOOOOHDXXQTQQQQZSSZSSSSSSSSKLSSHZZZZZZZZBBBBBBBBBBZZZZZZZZZZAAAAAA\r\nQQQYYYYYYYYYYYYYYYUUUUUUUUUUUWWWWWWWLLLLPPSSSSSSSSSSSFTFFFFFTTTTTTTPOOOOOOOOOOOHHXXZTQQDDSSSSSSSSSSSSSHHHHZZZZZZBBBBBBBBBBBBZZZZZZZZZZAAAAAA\r\nQQQYYYYYYYYYYYYZZYUUUUUUUUUKWWWWWWWWWWLLLLSSSSSSSSSSSFFFQQQQTTTTTTTPQQOOOOOOOOOHHZZZZZQDDDSSSSSSSSSSSSHHHZZQZZZBBBBBBBBBBBBBZZZZZZZZZZAAAAAA\r\nQQQQYYYQYYYYYYYUUUUUUUUUUUUKKWWQWWWWWWLLLLSSSSSSSSSSSSQQQQQQQQTTTTTTTTTTOOOOOOOXHZZZZZZZZDSSSSSSSSSSSSHHHZZZZZZCCBBBBBBBBBBBZZZZZZZZZZZAAAAA\r\nQQQQQQQQPRYYYYVUUUUUUUUUUUUKWWWWWWWWWWMLLLBBSSSSSSSSHQQQQQQQQQTTTTTTTTTTOOOOOOOOOOZZZZZZZSSSSSSSSSSSSSSHHHHZTZCCBBBBBBBBBBBBZZZZZZZZZZZAAAAV\r\nQQQQQQQQPPPPPYPUUPPUUUUUUUUUUWWWWWWWUWBBBBBBSSSSSSSSHHQQQQQQTTTTTTTTTTTTOOOOOVVVVZZZZZZZZDSSSSSSSSSSSSSSSHHSSSCCBBBBVBBBBBBZZZZZZZZZZZZAAAAV\r\nQQQQQQQQQPPPPPPPPPPUUUUUUUHHWWWWWWLWWWBBBBBBSSSSSSSSHHHQQQQQTTTTTTTTTTTTOOOOVVVZZZZZZZZZZSSSSSSSSSSSSSSSSXXSSSCCCSBSBBBBBBZZZZZZZZZVVZAAAAVV\r\nQQQQQQQQPPPPPPPPPPPPPPUUHHHHHHHWWWHHKWBBBBBRSSSQSZSSSHHQQQQQTTTTTTTTTTTTVVOVVZZZZZZZZZZZSSSSSFSSSSFSSSSSSSSSSSSSCSSSSBBBBZZZZZZZZZVVVZVVVVVV\r\nQQQQQQQQQPPPPPPPPPPPUUUHHHHHHHHHWHHHWWWBBBBBSSSQZZSHHHQQQQQQTTTTTTTTTGOOVVVVVZZZZZZZZZZZZSCCFFFFFFFSYYYYYSSSSSSSSSSSSBBBBBZZZZZZZVVVVVVVVVVV\r\nQQQQQQQQQPPPPPPPPPPPPPPOHWWHHHHHHHHHWWWBBBBBPZZZZZNJJHQQQQQQTTTTTTTTTGGGGVVVAAAAAZZZZZZZZZCSFFFFFFFFFYYYYYSSSSSSSSSSSSHBBBWZZZZZZVVVVVVVVVVV\r\nQQQQQQQQPPPPPPPPPPPPPPPPHWHHHHHHHHHHWWWBBBBBPZZZZZJJJJQQQQQQTTTTTTTTTGGGVVVVAAAAAZZZZZZZZSSSFFFFFFFFYYYYYYYSSSSSSSSSSHHBBZZZZZZZVVVVVVVVVVVV\r\nQQQQQQQQQPPPPPPPPPPPPPPPPPHHHHHHHHHHWWWBBBBBZZZZZZJJJQQQQQUQTTTTTTTTTGGVVVVVAAAAAZZZZZZZZSSSFFFFFFYYYYYYYYPSSSSSSSSSJJJBBQQQQZZZZVMVVVVVVVVV\r\nQQQQQQQQPPPPPPPPPPPPPPPPPPHHHHHHHHHWWWBBBVBBZZZZIZJJJJQQPQJQJGTTTTTTTGGGVVVVAAAAAZZZZZZZZSDFFFFFFFFYYYYYYYSSSSSSSSSJJJJJQQQQQZZZVVVVVVVVVVVV\r\nQQQQQSSSPPPPPPPPPPPIPPPPQPEHHHHHFNFFFWBBBVBBBBZPIJJJJJJQJJJJJJTTTTTTTGGVVVVNAAAAAAAAAZZJJDDDFFFFFFYYYYYYYYSSSOOSSSSJJJJJQQQQQQQVVVVVVVVVVVVV\r\nSNSSSSSSSPPPPPPPIIPIIIIPPPPXHHHHFFFFFBBBBCCCCYYIIIIJJJJJJJJJJJGGGGGGGGGGGVVNAAAAAAAAAZZZJDDDDFFFFFYYYYYYYYSSSOOSSSJJJJJQQQQQQQQQQVVVVVVVVVVV\r\nSSSSSSSUPPPPPPPPIIIIIIIIXPPXFFFFFFFFFBSBCCCCCCCIIIIJJJJJJJJJJGGGGGGGGGGGHNNNAAAAAAAAAZZZZZDDDDJVFFYYJYJJYOSSOOOPPSPPJJJJQQJIIIQQQVVVVVVVVVVV\r\nSXSSSSUUPPPPPPIIIIIIIIIIXXXXFFFFFFFFFFCCCCCCSCCIIIIIIJJJJJJJHHHHGGGGGGGGHNNNAAAAAAAAAZZZZVVDDDJJJJYYJJJJJOOOOOOPPPPJJJJJJJJIIQQEEENVVVVVVVVV\r\nSSSSSSSUPPPPIIIIIIIIIIIXXXFFFFFFFFFFFFFCCCCCCIIIIIIIIJJJJJJHHHHHHHGGGGGGGNNNAAAAAAAAAVVZVVVVDDJJJJJJJJJJJOOOOXOIIIIJJIJJJJIIIIQEEEVVVVVVVVVD\r\nSSSSSSSSXPPXIIIIIIIIIIIIIXFFFFFFFFFFCCCCCCCCCIIIIIIIIIJJHHHHHHHHHHHGGGGGGGNNNWWVAAAAAVVVVVVVDDDDJJJJJJJJJJJJOOOMOIJJIIJJIIIIIIIEEEEVVVVVVDDD\r\nSSSSSSSSXXPXXIIIIIIIIIIIIIIOFFFFFFFCCCCCCCCCCIIIIIIIIIHHHHHHHHHHHFGGGGGGGGGNNNNNAAAAAVVVVVVVVVDDJJJJJJJJJJOJOOOOOIIIIIIIIIIIIIEEEEEEVVVVVVVD\r\nSSSSSSSXXXXXXIIIIIIIIIIIIIIOFFFFFFFFCCCCCCCCIIIIIIIIIHHHHHHHHHHHHHLGGGGGGGGGNNNNAAAAAVVVVVVVVDDDJJJCCCJJJJOFOOOOOIIIIIIIIIIIIIEEEEEEQVRVVVVD\r\nSSSSSSSXXXXXIIIIIIIIIIIHIIOFFFFFFFFCCCCCCCCCIIIIIIIIIIVHHHHHHHHHYYQXGGGGEEEGGGNNNNVVVVVVVVVDDDJJJJCCCJJJJJOOOOOOOOOIIIIIIIIIIIEEEEEEQQFVFFFD\r\nSSSSSSSSSSXXXXXXXXIIIIIIIIOOOFFFFFFFCCCCCCCIIIIIIIIIIIHHHHHHHHHHYYQQGGLLEEGGGSVVVVVVVVVDDVDDDDDGKKKKCJJJJOOOOOOOOOFOOIIIIIIIWIWWEEEEEFFFFFFF\r\nSSSSSSSSXXXXXXXXXXIIIYYYIOOOOFFFMFMFCCCCCCCIIIIIIIIIIIHHHHHHHHHHYQQQQQQLEEGGGSVSSSVVVVVDDDDDDDDGKKKKKKOOOOOOOOOOOOOOOIIIWIWWWWWWWEEEEFFFFFFF\r\nSSSSSSSSXXXXXXXXXXIIOOYYIOOOFFFFMMMMCCCCCCCCIIIIIIIIIIHHHHHYHHHHYYQQQQQLEEEGSSSSSSVVVVDDDDGGGDGGKKKKKKOGOOOOOOOOOOOOOIIIWWWWWWWWWEEEEFFFFFHF\r\nSSSSSSSSXXXXXXXXXXXXXXXXXOOOOOOFMCCCCCCCCCCIIIIIIIIIIIBHHHYYHHHYYYQQQQQEEEEETTSSSSSVVDDDGGGGGGGGKKKGKKKGOOOOOOOOOOOOOOOOWWWWWWWWXXXEEFFFFHHH\r\nSSSSSSSXXXXXXXXXXXXXXXXXXOOOOOOOMOCCCCCCCCCIIIIIIIIIIBBHSSYYYYYYYYQQQQQQWEETTTTSTTVVVVDDGGDGGGGGKKKGGKGGOOOSOOOOOOOOOOWWWWWWWWWXXXXXEXXFFHHH\r\nSSSSSSXXXXXXXXXXXXXXXXXXXOOOOOOOOOOCCCCCCYIIIIIIIISISSSSSSSSYYYYYQQQQQQQWTTTTTTTTTTVDDDGGDDGGGGGGGGGGGGGGOOSSOOOOOOOOOWWWWWWWWWWWXXXXXXFFFFH\r\nSSSSSSSSXXXXXXXXXXXXXXXXXOOOOOOOOPPPCCCCYYIIEIIIISSSSSSSSSSYYYYYYQQQQQWWWWTTTTTTTTTTTDDDDDYGGGGGGGGGGWGGVOOSSNOOOOOWWOWWWWWWWWWWWXXGGGGGGFHH\r\nSSSSZZSXXXXXXXXXXXXXXXXXXOOOOOKKKKKKPCYYYYYYYOOOSSSSSSSSSSSSIYYIIQQQQQQQWTTTTTTTTTTTDDDDDYYYGGGGGGGGGGGSSSSSSSSWOOWWWWWWWWWQWWWWWXXGGGGGGHTH\r\nSSSSSSSSXXXXXXXXXXXXXXXXXOOAOOKKKKKKSYYYYYYYOOOSSSSSSSSSSIIIIIIIIQQQQWWWWTTTTTTTTTTTDDDDDDYYGYYGGGGGGGSSSSSSSSSWOOWWWWWWWWQQFFWWWXYGGGGGHTTT\r\nSSSSSSSSXXXXXXXXXXXXXXXXXAAAAAKKKKKKKKVYYYYOOOOSSSSSSSSSSSIIIIIIIIQQQQWWHATTTTTTTTTTDDDDDDYYYYYGGGGGGGGGGSSSSSSWWWWWWWWWWWQQFFFFWXYYYYGGHHTN\r\nSPPSSXXXXXXXXXXXXXXXXXXXXAAAAAKKKKKKKKVVVUUUUOOSSSSSSSSSSIIIIIIIIIQMQHHHHHHTTTTTTTDDDYYYYYYYYYGGGGGGGSUSSSSSSSWWWWWWWWWQQQQQQFFFYYYYYYHHHTTT\r\nSPPPXXXXXXXXXXXXXXXXXXXXXAAAAAKKKKKKKKAUUUUUUUOUUUSSSSSSSIIIIIIIIIIMMMHHHHHTTTTTTTTDDYYYYYYYYYGEEEEEEEEEESSSSSOOOOOOOOWWQQQQFFFFYYYYYYHTTTTT\r\nPPXXXXXXXXXXXXXXXXXXXXXXXAAAAAKKKKKKKKKAUUUUUUUUUUUSSJSSSIIIIIIIIIIIMMRHRRHTTWTTTTTDDYYYYYYYYYGEEEEEEEEEEEOOOOOOOOOOOOEEQQQQQYFYYYYYYYYYTTTT\r\nPPPXXXXXXXXXXXXXXAAAIIIAAAAAAAKKKKKKKKKAUUUUUUKKKKKKKJSJJIIIIIIIILLRRRRRRRHRWWWWTTDDYYYYYYYYYYYEEEEEEEEEEEOOOOOOOOOOOOEEQQQQQYYYYYYYYYYTTTTT\r\nPPPPPDXXXXXXXXXXXIANIIAAAAAAAAKKKKKKKKKUUUUUUUKKKKKKKJJJJITJJJIIILLLLRRRRHHRWRRWTTDTYYYYYYYYYYYEEEEEEEEEEEOOOOOOOOOOOOEEQQQQQYYYYYYYYYYTTTTT\r\nPPPDDCXXXXXXXXXXXIIIIAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKKKJJJJMJJJJILLLLLRRRRRRHRRRRRTTTTTYYYYYYEEEEEEEEEEEEEEEESSSOOOOOOOOEEOQQQYYYNNNYNNNYTTTTT\r\nPPPDDDDDDDXWXDDDIIIIIAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJLLJJJLLRRRRRRRRRCCCTCTTYYYYYYEEEEEEEEEEEEEEEESFFOOOOOOOOEEOOOQQYYNNNNNNNYYTTTT\r\nPPDDDDDDDDKDDDDDIIIAAAAAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJLLLRRRRRRRRRCCCCCCYYYYYYEEEEEEEEEEEEEEEESSFOOOOOOOOEEOCOQQQYNNNNNNNTTTTTT\r\nPPDDDDDDDDRRDDDDIHHHHHAAAAAAAAALKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJLLLLRRRRRRRRRLCCCYYYYYYYEEEEEEEEEEEEEEEESSSEEOOOOOEEECCQQQQNNNNNNNTTTTTTT\r\nPPPDDDDDDDRRDDDDDKHHHHAAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJLLLLRRRRRRRRLLCCCYDYYYYYEEEEEEEEEEEEEEECCCCEEOOOOOEEECCCQQQNNNNNNNNTTTTTT\r\nUUPPDDDDDDRDDDDDDKHHHHHHHHAAAAAAKKKKKKKKKKKKKKKKKKKKKKKJJJJJJJJJJLLLLLLLRRRRRRRLLCCOOYYAYFEEEEEEEEEEESSSSSSCCCEEOOOOOEEECCCCQNNNNNNNNNTTTTTT\r\nUUPUDDDUDDDDDDDDHHHHHHHHHHAAAAAAAAAAAKKKKKKKKKKKKKKKKKKJJJJJJJJJJLLLLLLRRRRRLLLALCCOOOAAEFEEEEEEEEEEELSSSHFCCCCFOOOOOCCCCCCCCKNNNNNNNNTTTTTT\r\nUUUUUUUUUUDDDDDDDDDHHHHHHHHHAAAAAAAASKKKKKKKKKKUXUQKKKKJBBBJJJJJLLDDLLLLLRRLLLLLLOCCOAAAEEEEEEEEEEEEELSHHHFCCFFFOOOOORRCCCCCCKKNNNNNNNNFFFFT\r\nUUUUUUUUUDDDDDDDTDHHHHHHHHHHAAAAAAAASKKKKKKKKKKSSSSKKKKSSBUJJJJJDDDDDDDLLDDLLLLLLOOOOOAEQEEEEEEEEEEEEEEHHFFFFFFFOOOOOCCCCCCCKKKKKKNNNNNFFFFF\r\nUUUUUUUUDDDDDDDDDDHHHHHHAAAAAAAAAAAASSSSSSSSSSSSSKKKKKKSSSUJJJJDDDDDDDDLLDDLLLLLOOOOOOOEEEEEEEEEEEEEEEEEETFFFFFFOOOOOOOOOOOUDKUUKBNNNFFFFFFF\r\nUUUUUUUUUDDDDDDDDDDDHHHWAAAAAAAAAAAASSSSSSSSSSDSSKKKKKKUUUUUUJJDDDDDDDDDDDDDLLOOOOOOOOESEEEEEEEEEEEEEEPFFFFFFFFFFFCCOOOOOOOUUUUUBBNNNFFFFFFK\r\nUUUUUUUUUUUDDDDDDDFFHWWWWWWWAAAAAAAASSSSSSSSSDDDUKKKKUUUDDUUUUJDDDDDDDDDDDLLLOOOOOOOOSEEEEEEEEEEEEEQQQPPPFFFFRROOOOOOOOOOOOUUUUUBBBNNFFFFKKK\r\nUUUUUUUUMUMDDDDDDDDDSWWWWWWWAAAAAAAAAPSSSSDSSDDUUUUUUUUUUDDDDDDDDDDDDDDDLDLLLOLOOOOOOFEEEEEEEEEEEEEQQQPPPFFFFFROOOOOOOOCCTUUUUUOYYYPNFFKKKKK\r\nUUUUUUUUMMMDDDDMMMMMMYWWWEWWWAAAAAADASSSSSDDDDDDDUUUUUUUDDDDDDDDDDDDDDDDLLLLLLLLOOOOOFVFFEFFEEEEEEQQQQQQMMMMMMROOOOOOOOBUUUUUUUYYYYYFFFFFKKK\r\nUUUUUUUUMMMMMMMMMMMMMMEEEEEEEAAAAAADDDSSSSDDDDDDDDUDUUUUUDDDDDDDDDDDDDTLLLLLLLLLOOOOOFFDFFFFEEEEEEQQQQQMMMMMMRROOOOOOOOUUUUUUUUUYYYYFFFKKKKK\r\nEEUUUUUUMMMMMMMMMMMMMMEEEENNEAAAAAADDDDDSDDDDDDDDDDDUUUUDDDDDDDDDDDDTTTLLLLLLLLLLLOOFFFFFFFFLLEUUUUJQQMMMMMMMMMOOOOOOOOUUUUUUUUUUYYFFFKKKKKK\r\nEEUUUUUMMMMMMMMMMMMMMMEQQNNNQAAAAADDDDDDTDDDDDDDDDDDDUUUUDUUDLLLDDDDTTTTTLLLLLLLLLLLLFFFFLLLLLEUUUUQQMMMMMMMMMMOOOOOOOORUUUUUUUUUYYFKKKKKKKK\r\nEEEEEUMMMMMMMMMMMMMPPPQQQNNNQQQAAAQQTTTTTTDDDDDDDDDDDUUUUUULLLLLLDDTTTTTTLLLLLLLLLLLLLFLFLLUUUUUUUUQQMMMMMMMMMMOOOOOOOOOOOOOOOUUUYYYKKKKKKKK\r\nEEEEMMMMMMMMKMMMMMFQQQQQQQNQQQQAQQQQQTTTTTDDDDDDDDDDDDUULLULLLLLTTTTTTTTLLLLLLLLLLLLLLLLLLLLUUUUUUUZZMZMMMMMMMMOOOOOOOOOOOOOOOUUUYYKKKKKKKKK\r\nEEEEEMMMMMMMGGGMMFFFQQQQQQQQQQQAQQQQQQTTTTDDDDDDDDDDDUUULLLLLLLLTDTTTTTTTLLLLLLLALALLAAAAALLLUUUUZZZZZZMMMMMMMMRRRIIRROOOOOOOOUUUUVKKKKKKKKK\r\nEEEEEEMEEEGGGGGGGFFFQGQQQQQQQQQQQQQQQTTTTTKDDDDDDDDDDUUULLLLLLLBTTTTTTTTTTTLLLLLAAAAAAAAAALLUUUUUZZZZZZZZMMIMMBIIIIIIROOOOOOOOUUBBKKKKKKKKKK\r\nEEPEPEMEEEGGGGGGGFFFGGQQQQQQQQQQQQQQQTTTTMDDDDDDDDDXXIIILLLLLLLBBBBBTTTTTTTLPPLLLLLAAAAAAAAAAUUUUUUUZZDZZMMIDDIIIBIIIIOOOOOOOOUBBBKKKKKKKKKK\r\nPPPPPEEEEEEGGGGGGGGGGQQQQQQQQQQQQQQTTTTTTMDDDDDDDDDXXXIILLLLLLLBBBTTTTTTTTTPPPLLLLLAAAAAAAAAAUUUUUUUZDDDDDIIAAAAAAAAAIOOOOOOOOUUKKKKKKKKKKKK\r\nJPPPPEEEEEGGGGGGGGGGGQQQQQQQQQQQQQQQTTTTDDDDDDDDDDDDDXIIILLRIIBBBTUTTKKKKKKPPTLTTTLAAVAAAAAAAUUUUUUUULDDDIAAAAAAAAAAAFOOOOOOOOUUKKKKKKKKKKKK\r\nJPPPLPPPPGGGGGGGGGGGGGQQQQQQQQVVNNNQTTTTTTDDDDDDDDDDDIIIIIIIIIIBTTTTTKKKKKKPPTTTTTTAAAAAAAAAUUUUUUUUUDDDDAAAAAAAAAAAAAAAOOOOOOFUFKKKKKKKKKKK\r\nJPPPPPPPWGGGGGGGGGZGGGGQQQQQVVVVVNNTTTTTTTTDDDDDDDIDIIIIIIIIIBBBBTTTTKKKKKKPPSSTTSAAAAAAAAAAUUUUUUUUUDDDDAAAAAAAAAAAAAAAFFFFFFFFFKKKKKKKKDDK\r\nJJJPPPPPWWWPPGGZGZZGGFGQFFVVVVVVVVNNNTTTTTTDDDDDDDIIIIIIIBBBIBBBBTTTKKKKKKKKPPSSTSAAAAAAAAAUUUUUUUUUUDDDDAAAAAAAAAAAAAAAFFFFFFFFFFKKKKKKDDDK\r\nJJPPPPPPPPPPPGZZZZZZGFFFFFFFVVVVVVNNNNTNNTTTTTDDIIIIIIIIIBBBIBBBBBPEKKKKKKKKPSSSSSSAAAAAAATTTUUUUUUDDDDDDAAAAAAAAAAAAAAAFFFFFFFSFFKKKDKKKPDD\r\nPPPPPPPPPPPPZZZZZZZZGGGFFFFFVVVVVVVVNNNNTTVVTTTDIIIIIIIIIBBBBBBBBBPPKKKKKKKKPPSSSSSAAAAAAATTTUUUUUTTDDDDDAAAAAAAAAAAAAAAFJFFFFFSFFKKKDDDDDDD\r\nPPPPPPPPPPPPZJJZZZZGGGGGGFFVVVVVFVNNNNNTTTTTTTTIIIIIIIIIIIBBBBBBBPPPKKKKKKKKPPSSSSSSAAAAAATTUUTTTTTTWDDDDDAAAAAAAAAAAAAAFJJFFFSSDFFKDDDDDDDD\r\nPPPPPPPPPPPPZZZZZZZZZZZGZFFFVVVVVVVNNNTTTATTTTTIIIIIIIIITTBTBBBPPPCKKKKKKKKKKKKKKKAAAAAAATTTTTTTTTTTWWDWWDDDDDDIEAAAAAAASSSFFSSDDDDKWDDDDDDD\r\nPNPPPPPPPPZZZZZZZZZZZZZZZIFIIIVVVNNNNNTTTTTTTTTTTTTIIIIITTTTBBBBPPCKKKKKKKKKKKKKKKSAAAAAAAATTTTTTWWWWWWWWDDDDDDDEAAAAAAASSSSSSSSTDDDDDDDDDDD\r\nNNNNPPPPPVZZZZZZZZZZZZZZIIIIIINNNNNNMTTTTTTTTTTTTIIIIIIITTTTBBBBPPCKKKKKKKKKKKKKKKSAATTTTTTTTTWWWWWWWWWWWDDDDDDDEAAAAAAASSSSSSSSSSDDDDDDDDDD\r\nNNNNNPPPPVZZZZZZZZZZZZZZIIIIIINNNNNNMMTTTTTTTTTTTRIIIIIITTTBBBBCCCCKKKKKKKKKKKKKKKAAAATTTTTTTTTWWWWWWWWWWDDDDDDDEEEEEEESSSSSSSSSSSDDDDDDDDDD\r\nNNNNNPNPVVZZZZZZZZZZZZZZIIIIIIINNNNNMMMTTTTTTTTTTTIIIIIQTTBBBBBBCCCKKKKKKKKKKKKKKKUVVTTTTTTTTTTWTWWWWWWWWDDDDDDDDDDEEEESSSSSSSSSSSLLDDDDDDDD\r\nNNNNNNNNNVZZZZZZZZZZZZZZIOIIIIIIINIMMMMMMTTTTTTLTIIIIIIIFBBBBBBBCCCKKKKKKKKKKKKKKKVVVVTTVTTTTTTWWWWWWWWWDDDDDDDDDEEEEEESSESLSSSSSSLLLDDDDDDD\r\nNNNNNNNZZZZZZZZZZZZOOIOOOOOIIIIIIIIMMMMMMTTTTTTPPPPPPIIFFBBBBBBBCCCKKKKKKKKKKKFFDDVVVVTVVTTTTTTTWYWWWWMMDDDDDDDDDEEEEEEEEESLOOOFSLLLLDGGGRDD\r\nNNNNNNNNZZZZZZZZZZZZOOOOOOOIIIIIIIIMMMMMMMTMTTTPPPPPPPIYBBBBBBBBBBCKKKCCCCFFFFFFVVVVVVVVVTTEETTTWWWWWWWDDDDDDDDDDEDEEEEEEEEOOOPSSLLLGGGGGDDD\r\nNNNNNNNNNNZZZZZZZZMOOOOOOIIIIIIIIIIIMMMMMMMMMMTTPPPPPPPYYBBBBBBBBBCCCCCCCFFFFFFFVVVVVVVVVVVEETTTWWWWWWWWQDDDDDDDDDDEEEEEEEOOOOPPPGGGGGGUUDDD\r\nNNNNNNNNNNNZZZZZZIIOOOOOOOOIICCIIIIIMMMMMMMMMPPTPPPPPPPYYBBBBBBBBBGCCCCCCFFFFFFXVVVVVVVVVVRREETTTWWWWWWQQQQDDDDDEEEEEEEEEEOOOOPPOOGGGGGGUGGG\r\nNNNNNNNNNNNZZZZZIIIVVOOOOOOOCCCIIIIIMMMMMMMMMPPPPPPPPPPYYBBGBBBBBGGGCCCKCRFFFFXXVVVVVVVVVRRRRUUUUUUWWFFFQQQQQQQIIIEEEEEEEOOOOOOOOOOGGGGGGGGG\r\nNNNNNNNNNNNNZIIIIIIVOOOFCCOOCCCIIIIMMMMMMMMMMPPPPPPPPOPFOGGGGGGBKCCCCCCOORFFXFXXVVVVVVVVVRRUUUUUUUUWWFFFIQQQQQIIIWEWEEEEEOOOOOOOOOOGGGGGGGGG\r\nNNNNNNNNNNIIIIIIIIIVOOOFCCCCCCCIIIIMMMMMMPPMMPPPPPPPPOOOOOGGGOOBCCCCCCCOOOAXXXXXXVVVVVVVVRUUUUUUUUFFFFFFIIIQIIHIWWWWEEEEEOOOOOOOOGGGGGGGGGGG\r\nNNNNNNNNNNIIIIBBIIIVVOCCCCCCCCCIIIMMMMMMMYPPPPPPPPPPOOOOOOGGGOOCCCCCCCCCOAAXXAXXXVVVVVVVJJJUUUUUUUFFFFFFIIIIIIIIWWWWEEEOOOOOOOLOOGGGGGGGGGGG\r\nNNNNNNNNNNNNIBBBBIBBBBCCCCCCCCCIIIIMMMMMYYPPPPPPPPPPOOOOOOOOOOOOCCCCCCAAYAAAAAAAAVVVVVVJJJJUUUUUUHFFFFFFIIIIIIIIWWWWEEEOOOOOOLLLGGGGGGGGGGGM\r\nNNNNNNNFNINIIBBBBBBBBCCCCCCCCCCCCIIMMMMMYYPPPPPPPPPPOOOOOOOOOOOOCCCCCAAAAAAAAOAOOOVVVVVJJJJJUJJHHHFFFFFFIIIIIIIIXTWWWEEOOTTOOLLLGGGGGGGGGGGG\r\nNNNNNNFFIIIIBBBBBBBBBCCCCCCCCCCCCIZVZZBBPPPPPPPPPPPPOOOOOOOOOOOOOCCCCCCCAAAAAOOOJJJYJJJJJJJJJFFFFFFFFFFFIIIIIIITXTWWEETTTTTLLLLLLGGGGGGGGGGS\r\nNNNNNNFIIIIIIBBBBBBBCCCCCCCCHCCYCZZZZZBBPPPPPPPPDPPOOOOOOOOOOOOCOCCCCCCCCCAAAOOOOJJJJJJJJJJJJFFFFFFFFFFFIIIIIITTTTATETTTTTLLLLLLLLGGGGGGGGGS\r\nFFFFFFFFIAAIIBBBBBBBCCCCCCCCHHHYZZZZZZBBPPPPPPDDDDOOOOOOOOOOOOOCCCCCCCCCCAJJJJOOOOJOJJJJJJJJJFFFFFFFFFFFIIIIIIIITTTTTTTTTTTTLLLLLLLYGSSSSSSS\r\nFFFFFFFFIFFFFBBBBBBBCCCCCCCCHHHHZZZZZBBPPPDPPPPDDOOOOOOOOOOOOOCCCCCCCCCCCUJJJJOOOOOOORRRJJJJJHHHHHHHFFFFIIIIIIIITTTTTTTTTTTLLLLLLLLLSSSSSSSS\r\nNNFFFFFFFFFFHOBBOOBCCRCCCCHHHHHIIIZZZBBBPPDPPPPDDDOOOOOOOOOOOOCCCCCCCCCCCUJJJJUUORRRRRRRJJJJJHNHHHHHFFFFIIIIITTTTTTTTTTTTTTLLLLLLLLLSSSSSSSS\r\nNFFFFFFFFFFHHOOOOOOOCCCCCCHHHHHHIZZZKUBUUUDDPPDDDDDDOOOOOOOOCCCCCCCCCCCCCUJJJJUUUZRRRRRRRJRJNNNNHHMHFFFFIIIIITTTTTTTTTTTTTLLLLLLLLLLLSSLSSSS\r\nNFFFFFFFFFFOOOOOOOOOOCOOCHHHHHHHIIIIUUUUUUDDPDDDDDDOOOOOOOOYCYCCCCCCCCCUUUJJJJUUURRRRRRRRRRJJJJNHVMYFFFFIIIIITTTTTTTTTTTZLLLLLLLLLLLLLLLSSSS\r\nFFFFFFFFFFFFOOOOOOOOOOOOCHHHHHHHIIIUUUUUUUUDDDDDDDOOOOOOOOOYCYCYYYJJJJJJJJJJJJUUURRRRRRRRRJJJJJMMMMMMMIIIIIIMTTTTTTTTTTTZZLLLLLLLLLLLLLLSSSS\r\nFFFFFFFFFFFFOOOOOOOOOOOOOHHHHHHIIIIUUUUUUUUUDDDDDDOOOOOOOOOYCYYYYCJJJJJJJJJJJJRRRRRRRRRRRJJJJJMMMMMMMMINIIIIMIDTTTTTTTTTZZLLLLLLLSSSSSLSSSSS\r\nFFFFFFFFFQFFOOOOOOOOOOOOOHHHHHHHHHIIUUUUUUUDDDDDDDOOOOOOOYYYYYYYYCJJJJJJJJJJUUUUUURRRRRRRJJJJMMMMMMMMNNNIIIIIITTTTTTTTTTZZLLLLLLLLLSSSSSSSSS\r\nFFFFFFQQQQFFOOOOOOOOOOOOOHHHHHHHHIIIUUUUUUDDDDDDDOOOOODDYYYYYYYYYCJJJJJJJJJJUUUUUUURRRRRRRJJMMMMMMMMMMONIOOIIITXTXXXXXXXTZLLLLLDDTSSTSSSSSSS\r\nFFFFFQQQQVFOOOOOOOOOOOOOHHHHHHHHHIIIUUUUUUDDDDDDDDDDDOODDYYYYYYYJJJJJJJJJJJJUUUUMUMRRRRRJJJJMMMMMMMMMOOOOOOIXXXXXXXXXXTTTTTTLLLLLTTSTSSSSSSS\r\nFFFFQQQQQVFFVOOOOOOOOOOOHHHHHHHHHHIIUUUUUDDDDDDDDDDDDDDDYYYYYYYYJJJJJJJJJJJJUUUUUUMMRRRRPJJJMMMMMMMMOOOOOOOIXOXXXXXXTTTTTTTTTTLLLTTTTSSSSSSS\r\nFFFFQQQQVVVFVVOUUUOOOOOHHHHHHHHHHHHHXUUUUDDDDDDDDDSSSSSSYSSSYYYYJJJJCYCUUUUUUUUUPUPPPPPPPJJJMMMMMMMMOOOOOOOOOOOXXXXXXTTTTTTTTTTTTTTTTSSSSSSS\r\nFFFFQVQQVVVVVVPUOOOOOOOHHHHHHHHHHHHHXXUDDDDDDDDDDDDSSSSSSSSSSYYYJJJJYYYYUUUUUUPPPPPPPPPPPJJMMMMMMMMXRROOOOOOOOOOXTTTXTTTTTTTTTTTTTTTTSSSSSSS\r\nVVVFVVVQVVVVPPPOOOOOLLAJHHHHHHHHHHHXXXUDDDDZDDDDDDDSSSSSSSSSSSSSJJJJVYYSSUUPPPPPPPPPPPPPPPPIIMMMMMMXROOOOOKOOOXXXXXTTTTTTTTTTTTTTTTTTSSSSSSS\r\nVFFFFVVVVVPPPPPPPONAAAAAHHHHHHHXXXHHXXUDDDZZDDZZDDDDSSSSSSSSSSSSJJJJYYYSSSPPPPPPPPPPPPPIIPIIIMMMMMXXXXXOOOOOOOXXXXXXTTTTTTTTTTTTTTTTSSSSSSSS\r\nVVVFFVVVVVVPPPPPPPPPAAAAAAAAAAXXXXHXXXXZZZZZZZZZZDDDSSSSSSSSSSSSJJJJYYSSSSPPPPPPPPPPPPPPIPPIIMMMMXXXXXXXXOOXOXXXXXXTTTTTTTTTTTTTTTTTSSSSSSSS\r\nVVVVVVVVVVVVPPPPPNPKAAAAAAAAJAXXXXXXXXXXZZZZZZZZZDDSSSSSSSSSSSSZZZZZYYYSSPPPPPJPEPPPPPIIIIIIMMMMMXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTSSSSSSSS";
    }
}
